---
AWSTemplateFormatVersion: '2010-09-09'

Description: Create IAM Role for EMR Studio Service Role

Resources:

  StudioServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - elasticmapreduce.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: EmrStudioServiceRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:AuthorizeSecurityGroupEgress
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:CreateSecurityGroup
            - ec2:DescribeSecurityGroups
            - ec2:RevokeSecurityGroupEgress
            - ec2:CreateNetworkInterface
            - ec2:CreateNetworkInterfacePermission
            - ec2:DeleteNetworkInterface
            - ec2:DeleteNetworkInterfacePermission
            - ec2:DescribeNetworkInterfaces
            - ec2:ModifyNetworkInterfaceAttribute
            - ec2:DescribeTags
            - ec2:DescribeInstances
            - ec2:DescribeSubnets
            - ec2:DescribeVpcs
            - elasticmapreduce:ListInstances
            - elasticmapreduce:DescribeCluster
            - elasticmapreduce:ListSteps
            Resource: "*"
          - Effect: Allow
            Action: ec2:CreateTags
            Resource: arn:aws:ec2:*:*:network-interface/*
            Condition:
              ForAllValues:StringEquals:
                aws:TagKeys:
                - aws:elasticmapreduce:editor-id
                - aws:elasticmapreduce:job-flow-id
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetEncryptionConfiguration
            - s3:ListBucket
            - s3:DeleteObject
            Resource: arn:aws:s3:::*
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:*:*:secret:*

Outputs:
  IAMRole:
    Value: !Ref StudioServiceRole
    Description: Name of IAM Role for EMR Studio Service Role 
  IAMRoleArn:
    Value: !GetAtt StudioServiceRole.Arn
    Description: ARN of IAM Role for EMR Studio Service Role
